Vagrant.configure("2") do |c|
  c.berkshelf.enabled = false if Vagrant.has_plugin?("vagrant-berkshelf")
  c.vm.box = "centos67"
  c.vm.box_url = "/home/aman/chef-repo/bento-os/opscode_centos-6.7_chef-provisionerless.box"
  c.vm.hostname = "default-centos67"
  c.vm.network(:private_network, {:type=>"dhcp"})
  c.vm.synced_folder ".", "/vagrant", disabled: true
  c.vm.provider :virtualbox do |p|
  end
end
