# Generated by Chef
# Do not make manual changes

default['php']['elver'] = 'el7'
default['php']['output_buffering'] = 4096
default['php']['max_execution_time'] = 350
default['php']['max_input_time'] = 350
default['php']['memory_limit'] = '512M'
default['php']['display_errors'] = 'Off'
default['php']['post_max_size'] = '40M'
default['php']['upload_max_filesize'] = '30M'
default['php']['max_file_uploads'] = 25
default['php']['date_timezone'] = 'Asia/Kolkata'
default['php']['shm_size'] = '32M'
